import Head from 'next/head'
import Image from 'next/image'
import {AiFillFastBackward, AiFillFastForward} from 'react-icons/ai'
import {BsArrowUpRight} from 'react-icons/bs'
import {IoIosPlay} from 'react-icons/io'
import {HiOutlineChevronDown, HiOutlineChevronUp} from 'react-icons/hi'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

export default function Home() {
  const [active, setActive] = useState(true)

  const drop = () => {
    setActive(!active)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.bg}>
          <img src='/blind.png' />
        </div>
        <div className={styles.blur}></div>
      <main className={styles.main}>
        
        <div className={styles.left}>
          <div className={styles.leftTop}>
            <p>FRA 01/JAN</p>
            <div>
              <BsArrowUpRight color='black' />
            </div>
          </div>
          <div className={styles.currentSong}>
            <div className={styles.previewImg}>
              <img src='/blind.png' />
            </div>
            <p>The Weeknd - Blinding Light</p>
            <div className={styles.controls}>
              <AiFillFastBackward style={{cursor: 'pointer'}} />
              <div></div>
              <IoIosPlay style={{cursor: 'pointer'}} />
              <div></div>
              <AiFillFastForward style={{cursor: 'pointer'}} />
            </div>
          </div>
        </div>
        <div style={{ height: active ? '100%' : '', }} className={styles.right}>
          <div onClick={drop} style={{marginBottom: active ? '0px' : '0px'}} className={styles.dropDown}>
            <p>Songs</p>
            {active ? <HiOutlineChevronUp/> : <HiOutlineChevronDown /> }
          </div>
          {active ? <div className={styles.dropDownList}>
            <p>Blinding Light - The Weeknd</p>
            <p>Rapid Fire - Cruel Santino</p>
            <p>Go Away - Fireboy DML</p>
            <p>Starlight - Dave</p>
            <p>As it Was - Harry Style</p>
            <p>Bandana - Fireboy Dml</p>
            <p>Frozen - Madonna</p>
            <p>Dandelions - Ruth B</p>
            <p>Dandelions - Ruth B</p>
            <p>Dandelions - Ruth B</p>
            <p>Dandelions - Ruth B</p>
            <p>Dandelions - Ruth B</p>
            <p>Dandelions - Ruth B</p>
            <p>Dandelions - Ruth B</p>
          </div>
          : null }
        </div>
      </main>

      
    </div>
  )
}
